package org.jboss.quickstarts.ws.jaxws.samples.retail.profile;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-26T11:34:07.648+10:30
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://org.jboss.ws/samples/retail/profile", name = "ProfileMgmt")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProfileMgmt {

    @WebMethod
    @WebResult(name = "getCustomerDiscountResponse", targetNamespace = "http://org.jboss.ws/samples/retail/profile", partName = "getCustomerDiscountResponse")
    public DiscountResponse getCustomerDiscount(

        @WebParam(partName = "getCustomerDiscount", name = "getCustomerDiscount", targetNamespace = "http://org.jboss.ws/samples/retail/profile")
        DiscountRequest getCustomerDiscount
    );
}
