package org.jboss.quickstarts.ws.jaxws.samples.retail.profile;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-26T11:34:07.688+10:30
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "ProfileMgmtService",
                  wsdlLocation = "file:/C:/data/repos/quickstart/jaxws-retail/src/main/webapp/WEB-INF/wsdl/ProfileMgmtService.wsdl",
                  targetNamespace = "http://org.jboss.ws/samples/retail/profile")
public class ProfileMgmtService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://org.jboss.ws/samples/retail/profile", "ProfileMgmtService");
    public static final QName ProfileMgmtPort = new QName("http://org.jboss.ws/samples/retail/profile", "ProfileMgmtPort");
    static {
        URL url = null;
        try {
            url = URI.create("file:/C:/data/repos/quickstart/jaxws-retail/src/main/webapp/WEB-INF/wsdl/ProfileMgmtService.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProfileMgmtService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/data/repos/quickstart/jaxws-retail/src/main/webapp/WEB-INF/wsdl/ProfileMgmtService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProfileMgmtService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProfileMgmtService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProfileMgmtService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ProfileMgmtService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProfileMgmtService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProfileMgmtService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ProfileMgmt
     */
    @WebEndpoint(name = "ProfileMgmtPort")
    public ProfileMgmt getProfileMgmtPort() {
        return super.getPort(ProfileMgmtPort, ProfileMgmt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProfileMgmt
     */
    @WebEndpoint(name = "ProfileMgmtPort")
    public ProfileMgmt getProfileMgmtPort(WebServiceFeature... features) {
        return super.getPort(ProfileMgmtPort, ProfileMgmt.class, features);
    }

}
